### ISSUE TITLE
Drawdown Calculations

### ISSUE THREAD

**Issue by DominicPazzulaFRG** [FinancialRiskGroup/SASPerformanceAnalytics#102]
The R package has a lot of functionality around calculating and displaying drawdown information.

Implement

1. table.Drawdowns
2. maxDrawdown
3. chart.Drawdown
4. table.DrawdownsRatio

Each will probably require additional macros to be implemented.

**Comment by DominicPazzulaFRG** [comment]
Feel free to split this up into multiple Issues for easier tracking.

**Comment by Gnaymie** [comment]
Done by #119 - #162
