### ISSUE TITLE
Create list of functions in R and SAS

### ISSUE THREAD

**Issue by DominicPazzulaFRG** [FinancialRiskGroup/SASPerformanceAnalytics#15]
Go through the R library and list the functions available.  Go through the SAS library and list the functions available.  Create a spreadsheet comparing the two.  Assign an order of importance to each function in R, not yet available in SAS.

**Comment by Gnaymie** [comment]
[function_list.xlsx](https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/files/136898/function_list.xlsx)

**Comment by Gnaymie** [comment]
Edited one.
[Function List.xlsx](https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/files/136979/Function.List.xlsx)
