### ISSUE TITLE
Review Parameter Consistency

### ISSUE THREAD

**Issue by DominicPazzulaFRG** [FinancialRiskGroup/SASPerformanceAnalytics#16]
Review parameters in function calls.  

Do we consistently name parameters?
Do we consistently assign default values?
Do we properly document the parameter usage in the comments?

Create a spreadsheet detailing the parameters we use.  Use this to find areas of inconsistency.

**Comment by Gnaymie** [comment]
[parameters.xlsx](https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/files/153535/parameters.xlsx)

**Comment by Gnaymie** [comment]
[parameters.xlsx](https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/files/165988/parameters.xlsx)

Updated parameter file.

**Comment by Gnaymie** [comment]
[parameters.xlsx](https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/files/166207/parameters.xlsx)

Final version.

**Comment by Gnaymie** [comment]
Fixed by commit https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/commit/286bc97433a9e6cf79df0908da0df19f1da40803

**Comment by Gnaymie** [comment]
Updated by 
[parameters.xlsx](https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/files/277958/parameters.xlsx)
