### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by DominicPazzulaFRG** [FinancialRiskGroup/SASPerformanceAnalytics#17]
Review current tests.  Do we have adequate coverage?  Do we test each permutation of options?

Create a document detailing where we need additional tests.

**Comment by DominicPazzulaFRG** [comment]
Also list any currently failing tests.

**Comment by holinus** [comment]
[input setting.xlsx](https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/files/136985/input.setting.xlsx)

**Comment by holinus** [comment]
Stating to add test function for every macro with more parameter combinations.

**Comment by Gnaymie** [comment]
Passed Tests
[Test Coverage.xlsx](https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/files/278042/Test.Coverage.xlsx)

**Comment by Gnaymie** [comment]
Updated tests coverage notes.
Cells in pink are the parameters to be tested,what in green are macros completed test.
[Parameters & Test.xlsx](https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/files/279874/Parameters.Test.xlsx)

**Comment by Gnaymie** [comment]
Done by #111
