### ISSUE TITLE
Problem for definition of M squared

### ISSUE THREAD

**Issue by Gnaymie** [FinancialRiskGroup/SASPerformanceAnalytics#181]
The definition of M squared in CFA book4 reading 41 is (Rp-Rf)*sigmaM/sigmaP+Rf-Rm, while the definition in R document can be simplified as (Rp-Rf)*sigmaM/sigmaP+Rf, and the last one is what we used in our SAS package. Should we edit it to make it consistent with CFA definition?

**Comment by DominicPazzulaFRG** [comment]
My CFA Level 1 review books are at the office, is that what you referenced?  

Wikipedia is consistent with the R document: https://en.wikipedia.org/wiki/Modigliani_risk-adjusted_performance

Discussion on Analyst Forum (useful place for CFA candidates) would seem to indicate it is a total return (not incremental over Rm).  http://www.analystforum.com/forums/cfa-forums/cfa-level-iii-forum/91322170

But a PPT from CFA Institute is consistent with your reference to the CFA study material: https://www.cfainstitute.org/learning/products/publications/inv/Documents/investments_chapter6.pptx

I think the original paper by Modigliani and Modigliani was the R definition.  It was meant to be a ranking statistic like Sharpe Ratio.  The CFA definition makes it easier to see the value add over the benchmark.  

Add an option to report the M2 statistic NET of the Benchmark.  NET=TRUE use the CFA formula.  NET=FALSE use the Original/R formula.

Update documentation accordingly.  Create tests for both.  You will have to manually subtract the Benchmark Return after calling the R function.

**Comment by DominicPazzulaFRG** [comment]
Forgot to add that the default should be NET=FALSE

**Comment by Gnaymie** [comment]
Thank you for your reply. I referenced the E-book of CFA level 1 for 2016. 

I'm going to add NET parameter and tests for both.

**Comment by Gnaymie** [comment]
Done by #188
