### ISSUE TITLE
Create LPM macro

### ISSUE THREAD

**Issue by Gnaymie** [FinancialRiskGroup/SASPerformanceAnalytics#250]
The one calculate a lower partial moment for a time series.

**Comment by Gnaymie** [comment]
The definition of lower partial moment varies. 
In _Portfolio Selection and Lower Partial Moments_, the definition is
![image](https://cloud.githubusercontent.com/assets/17015619/16244362/9425649e-37c9-11e6-993a-0a31a94776fe.png)
and this one is consistent to which in wikipedia.

In Huffman S.P. & Moll C.R., "The impact of Asymmetry on Expected Stock Returns: An Investigation of Alternative Risk Measures", Algorithmic Finance 1, 2011 p. 79-93, the reference in R documentation, LPM about mean is defined by
![image](https://cloud.githubusercontent.com/assets/17015619/16244531/77560192-37ca-11e6-92ca-c9c7d2ae537e.png).
The difference between this and above is the denominator, here, the sum divided by the number of non-missing observations that less than threshold, while above it divided by the number of whole observations. In this case, we can add group as an option as what we did in upside_risk.sas.

I can't find any ref for the definition of LPM about mean used in R file : the LPM with about_mean=true calculates LPM about **the mean under the threshold**. 

Do we build LPM.sas consistent with definition in R or base on the second ref? @DominicPazzulaFRG

**Comment by DominicPazzulaFRG** [comment]
Calculate it both ways with an option to switch between the two methodologies.

**Comment by Gnaymie** [comment]
Done by #253, #254
