### ISSUE TITLE
Probable mistake in R code CAPM.epsilon

### ISSUE THREAD

**Issue by holinus** [FinancialRiskGroup/SASPerformanceAnalytics#268]
In the book of Carl Bacon, Practical Portfolio Performance Measurement and Attribution, second edition 2008, p.72, the regression equation of CAPM is:
![k0ige bgicwp0dj orlai2l](https://cloud.githubusercontent.com/assets/17033254/16665877/27a268da-4453-11e6-9827-95ec96bcc82f.png)

So epsilon can be calculated as:
![uja6nto qerfya5d p nbp](https://cloud.githubusercontent.com/assets/17033254/16665929/5829deac-4453-11e6-8821-146735dae2ac.png)

In R documentation, the equation is missing Rf:
![0qch91qb xwg9fy1 8v_8](https://cloud.githubusercontent.com/assets/17033254/16666005/bd69d3d0-4453-11e6-8a9d-d3b7269c0ed7.png)

In R code, the formula is different from that in the R documentation, but still wrong:
![vdo yala_ fbe ov g4c](https://cloud.githubusercontent.com/assets/17033254/16666048/f0325d64-4453-11e6-8538-93c34e28dcdb.png)

It should be -Rf + Rp instead of Rf + Rp.

**Comment by DominicPazzulaFRG** [comment]
definitely should be -Rf + Rp.  

The good part is that when you do the regression in SAS, you can have PROC REG output the residuals and you don't have to do the math.

You could do the same in R, too.

**Comment by Gnaymie** [comment]
Done by #277
