### ISSUE TITLE
Inconsistency of definitions of Sharpe_Ratio, SharpeRatio_annualized, and Adjusted_SharpeRatio

### ISSUE THREAD

**Issue by Gnaymie** [FinancialRiskGroup/SASPerformanceAnalytics#275]
The calculation we used in Sharpe_Ratio is 
![image](https://cloud.githubusercontent.com/assets/17015619/16808809/f8dab730-48eb-11e6-851e-dd862ee1acc5.png)

In SharpeRatio_annualized is 
![image](https://cloud.githubusercontent.com/assets/17015619/16808869/42d935dc-48ec-11e6-81c9-c75ab9d887dc.png)

While in Adjusted_SharpeRatio is
![image](https://cloud.githubusercontent.com/assets/17015619/16808992/a6fbd542-48ec-11e6-81a5-ede3d7c11e37.png)

The problem is Rf. In first two SR, Rf is risk free rate with scale correspond to Ra, for example, if we input daily returns, then Rf is daily risk free rate. In Adjusted_SR, no matter what Ra we put in, Rf should be yearly risk free rate. 

For the sake of consistency of our package, I recommend editing the calculation of Adjusted_SharpeRatio, replacing this part in Adj_SR with %SharpeRatio_annualized. What do you think? @DominicPazzulaFRG

**Comment by DominicPazzulaFRG** [comment]
I concur.

**Comment by Gnaymie** [comment]
Done by #277
