### ISSUE TITLE
Consolidate Method= parameter

### ISSUE THREAD

**Issue by DominicPazzulaFRG** [FinancialRiskGroup/SASPerformanceAnalytics#30]
We switch between LOG|DISCRETE and GEOMETRIC|ARITHMETIC following R.  Consolidate to LOG|DISCRETE for all macros.

Ensure tests continue to pass as you make changes.

**Comment by Gnaymie** [comment]
Fixed with pull request #39

**Comment by Gnaymie** [comment]
Fixed by pull request #39
