### ISSUE TITLE
"regLine" option appears in the comment of Chart_Regression.sas

### ISSUE THREAD

**Issue by holinus** [FinancialRiskGroup/SASPerformanceAnalytics#34]
In line 21 and 22 of Chart_Regression.sas, options "cl" and "degree" are dependent on "regLine". However, "regLine‘ is not a input in this macro.
Chart_Scatter.sas uses "regLine" as one of the input.

**Comment by DominicPazzulaFRG** [comment]
remove the regLine part of the comment.

**Comment by holinus** [comment]
Fixed by https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/commit/809ea96657c2b490894820fdd92f43732c34982d
