### ISSUE TITLE
Option "outCentered" in return_certered.sas 

### ISSUE THREAD

**Issue by holinus** [FinancialRiskGroup/SASPerformanceAnalytics#35]
In the comment of return_centered.sas, option "outCentered" is dependent on "updateInPlace", which is not the input.

**Comment by DominicPazzulaFRG** [comment]
Agree.  Please update

**Comment by holinus** [comment]
Fixed by commit https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/commit/809ea96657c2b490894820fdd92f43732c34982d
