### ISSUE TITLE
Probable comment typo in TrackingError.sas

### ISSUE THREAD

**Issue by holinus** [FinancialRiskGroup/SASPerformanceAnalytics#36]
In TrackingError.sas, line 10, it says "if add_annualized= TRUE". I think it actually means "if annualized =TRUE".

**Comment by DominicPazzulaFRG** [comment]
I agree.  Please update

**Comment by holinus** [comment]
Fixed by commit https://github.com/FinancialRiskGroup/SASPerformanceAnalytics/commit/809ea96657c2b490894820fdd92f43732c34982d
