### ISSUE TITLE
Surface option for divisor for Std calcs

### ISSUE THREAD

**Issue by DominicPazzulaFRG** [FinancialRiskGroup/SASPerformanceAnalytics#44]
We use PROC MEANS/SUMMARY to calculate standard deviation.  PROC MEANS/SUMMARY has an option VARDEF= to control the divisor.  

http://support.sas.com/documentation/cdl/en/proc/68954/HTML/default/viewer.htm#n1qnc9bddfvhzqn105kqitnf29cp.htm

To all macros that calculate standard deviation, or call macros that do, add VARDEF= as a parameter.  Valid values are {N,DF}.  DF should be set to the default.  

Add VARDEF=&VARDEF to PROC MEANS/SUMMARY calls.

**Comment by Gnaymie** [comment]
Done by #75
