### ISSUE TITLE
Create macro to annualize a single value

### ISSUE THREAD

**Issue by DominicPazzulaFRG** [FinancialRiskGroup/SASPerformanceAnalytics#45]
We have times where we need to annualize a single value.  RF is a common example.

Create a macro to annualize a single value.  The macro should return the value.

Once this is done, we will need to update code in other macros where needed.

**Comment by DominicPazzulaFRG** [comment]
Create tests.

**Comment by DominicPazzulaFRG** [comment]
This links to #46

**Comment by Gnaymie** [comment]
Add test by merge #62
