### ISSUE TITLE
Problems from Adjusted_SharpeRatio.sas

### ISSUE THREAD

**Issue by holinus** [FinancialRiskGroup/SASPerformanceAnalytics#47]
1. The main macro needs to be adjusted with respect to %return_excess() and %return_annualized().
2. Before calling corresponding R function, the input dataset needs to be changed to be consistent with R's way of dealing with return.
3. To test with different scaler parameter, we need to use %return_accumulate() to aggregate returns. Tests for %return_accumulate() are needed.

**Comment by Gnaymie** [comment]
Done by #186
